### ISSUE TITLE
PSharpCompiler should link external assemblies

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [p-org/PSharp#11]
I'm working on a project that depends on some external assemblies.  When I compile it with PSharpCompiler, the assemblies are not copied into the output directory and the program fails to load them at runtime.  It looks like the code to link external assemblies is unfinished:

https://github.com/p-org/PSharp/blob/master/Source/LanguageServices/Compilation/CompilationEngine.cs#L293

Workaround: Build once with Visual Studio, then compile and test with PSharpCompiler as desired.  The external assemblies remain in the output directory, so the program works.

**Comment by mattmccutchen-microsoft** [comment]
This issue is no longer a priority for me.  I realized that my project needs to download NuGet packages, so I need to build once with Visual Studio anyway.

**Comment by pdeligia** [comment]
Hi Matt, I am aware of this issue and had the same problem with Cheng's code and had to do it manually as you said. I not 100% sure what is the best way to make sure they are properly copied using the available APIs (although I did not spend more than an hour looking for a good solution). If you are aware of a good way please let me know, else I will try to find out (but as a low priority for now). Thanks.
