### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#117]
We should add support for .NET Core (https://www.microsoft.com/net/core), the new high-performance, cross-platform .NET runtime, and eventually transition to it as the main build target. This will allow P# to work on any operating system and device that .NET Core supports out of the box. This is more of a longer term task, does not require immediate action.

**Comment by alexreinking** [comment]
The core [P compiler](https://github.com/p-org/P) targeting P# is being ported to .NET Core. We should evaluate what it will take to support .NET Core in P#. As the lead developer on the new P compiler, I would be glad to help with this.

**Comment by akashlal** [comment]
@alexreinking My understand was that the P compiler will emit P# code and stop at that. In that sense, while it is useful for P# to support .NET code, it is not a blocker. Is this correct? Please feel free to take the first stab at this. The P# team can get involved as we get a better sense of the work involved.

**Comment by shazqadeer** [comment]
Yes, it is not a blocked to finishing the compiler work. But, the full benefit of porting the compiler over to .NET Core will not be realized until the runtime is also .NET Core.  Cross-platform is a big deal in my team in Azure.   Our C# code base targets .NET Core.

**Comment by pdeligia** [comment]
@shazqadeer I just added support for .NET Core/Standard (tested it in both Windows and Linux).

1. The production runtime is fully ported.
2. The tester currently works only in sequential mode (no portfolio or parallel testing) because it needs quite a bit of work to change the WCF dependency (which we need for spawning multiple testing processes) which is not supported in .NET Core.
3. The rewriter/compiler (from the high level P# syntax to the C# library version) is not ported yet because of some missing APIs in .NET Core (which should be available soon'ish though).

**Comment by shazqadeer** [comment]
Great milestone, congrats!  Moving to .NET Core is very important going forward since we want to make P# and RSM a compelling option for both first-party and third-party cloud services.

**Comment by alexreinking** [comment]
This is great news! The P# backend is coming along nicely, and it will be great to break the dependency on Windows-specific libraries.

**Comment by shazqadeer** [comment]
Azure Blockchain team is considering taking a dependency on P#.  Our production and test environment needs to be on .NET Core.  Based on the original post by @pdeligia, my understanding is that P# already satisfies our requirement because we can run PSharpTester on .NET Core in sequential mode.  That would be fine for us. But I just wanted to confirm.

**Comment by akashlal** [comment]
That is correct. We should be able to support the parallel mode in the tester by the time your team gets warmed up. The missing part that might take time is the high level syntax.

Akash

**Comment by shazqadeer** [comment]
Thanks for the clarification.  High level syntax is not a big deal.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
