### ISSUE TITLE
Throw exception on assertion failure

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#124]
Instead of calling `Environment.Exit`

**Comment by pdeligia** [comment]
We might want to properly propagate this back to the user somehow (e.g. based on your previous proposal). I have to double check the implementation, but if we throw the exception it might silently kill the task, without propagating to the user, because the task is fire-and-forget.

**Comment by akashlal** [comment]
Good point. As first step, the exception should kill the runtime. The next step would be to propagate the exceptions through the machines before it kills the runtime.

**Comment by pdeligia** [comment]
Done in #146
