### ISSUE TITLE
Defend against Tasks not under our control

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#125]
This is for the bug-finding mode. We should assert that a P# API cannot be called from a Task that is not under the control of our scheduler because likely this will lead to multiple issues with `PsharpTester`.

**Comment by pdeligia** [comment]
Self-assigned me as I am testing this in the `async`/`await` branch.

**Comment by pdeligia** [comment]
Done in 3378cd2f1498349bd2adafc392114c8b4c96d36b
