### ISSUE TITLE
Data race on MachineId.IdCounter

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#13]
I am getting a rare exception in `Runtime.Send` at the line:
```
var machine = PSharpRuntime.MachineMap[mid.Value];
```
The exception is `System.Collections.Generic.KeyNotFoundException`.

I think the race is in the constructor of `MachineId` on the line that does `MachineId.IdCounter++`. If two machines are created concurrently from different threads, then there can be a race on this variable. Perhaps this can be replaced with `Interlocked.Increment(ref IdCounter) - 1`. 

It is quite confusing to explain why this race leads to the above exception, but I think it makes sense and, at the least, I think there is a data race on `MachineId.IdCounter` (when creating machines from different threads).

**Comment by pdeligia** [comment]
Hi Paul, this is interesting, let me have a look!

**Comment by pdeligia** [comment]
There was actually another race, in the TypeIdCounter (mostly used for logging), so instead of using an `Interlocked.Increment`, I used a lock for the whole constructor. I think f2c5e2e0b2dce8824e54867bf4b577998ca7d3da should fix this issue now.

**Comment by pdeligia** [comment]
Closing this issue for now.
