### ISSUE TITLE
Remove Runtime.GetCurrentMachineId and Runtime.Receive

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#140]
Should we remove these two runtime APIs? This will allow us to also remove `TaskMap` from the production runtime, simplifying things.

`GetCurrentMachineId ` is used from non-P# machine code to get access to the underlying `MachineId` (the assumption is that the task calling this API is the same task that executes the machine).

`Receive` is used to wait upon an event from non-P# machine code (again, the assumption is that the task calling this API is the same task that executes the machine).

I believe that both APIs can be replaced by exposing some sort of callback from the machine. The assumption that the machine task must call these APIs, makes it safe to use (as long as the user respects the assumption of course).

We mainly use them in the [PSharpModels](https://github.com/p-org/PSharpModels) repository:
- https://github.com/p-org/PSharpModels/search?utf8=%E2%9C%93&q=GetCurrentMachineId
- https://github.com/p-org/PSharpModels/search?utf8=%E2%9C%93&q=Runtime.Receive&type=Code

I am not sure if we are still working on this repo, but we might want to update it if we make this change.

**Comment by akashlal** [comment]
Nar uses both these APIs. Let us discuss his code patterns before implementing this change. I would also like to discuss the topic of testing in production mode (see #142 ) before we choose to remove any assertions from the production runtime.

In general, I support making the runtime more lightweight. If we can pull off things like async-await without needing `TaskMap` then we should try to get rid of it.

The `PSharpModels` repository is not being actively used and we don't have to worry about keeping it updated.

**Comment by pdeligia** [comment]
Done in #148
