### ISSUE TITLE
Update manual/wiki

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#152]
We should probably update the pdf manual and wiki (or preferably just the wiki and remove the pdf manual so we do not need to maintain both of them), and enrich them with detailed description of advanced P# features, programming guides, etc. This is a long-term task (everyone on the team can contribute).

**Comment by akashlal** [comment]
Added a page on async-await: https://github.com/p-org/PSharp/wiki/Async-Await-Support-in-P%23

**Comment by pdeligia** [comment]
Related to #307.
