### ISSUE TITLE
GC optimizations

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#179]
There are a couple of optimizations that can be done to improve GC-related performance during runtime. Will get to do these at some point soon.

**Comment by pdeligia** [comment]
One obvious optimization is to cache the name of each state. We are already caching state instances (they are created only once). However, every time we query the name of the current state, we allocate a new string, and re-compute the format of the string:

https://github.com/p-org/PSharp/blob/master/Libraries/Core/Library/Machine.cs#L192

In experiments, this causes quite a bit of churn in Gen2, since we query this property all the time (for logging). Solution: caching the string at state creation, which significantly reduces the number of Gen 2 collections.

There are more string-related GC problems that we can improve with caching (instead of re-computing/re-allocating each time).

**Comment by formlesstree4** [comment]
Would something like using Lazy<T> to initialize the name work? We get the benefit of Lazy<T> being thread-safe (if created properly), and also only creating the string once.

Although, looking through https://github.com/p-org/PSharp/blob/master/Libraries/Core/Library/Machine.cs, I'm not sure if it's a candidate for Lazy<T> or not.

**Comment by pdeligia** [comment]
Thanks, @formlesstree4. In our case, I think creating the `string` that corresponds to a machine/state name once and storing it for further reuse during logging (instead of allocating the same string each time) is probably the best and simplest way. I do not think `Lazy<T>` is a good candidate here.

**Comment by pdeligia** [comment]
Performance opts were done in #425. Will revisit as necessery.
