### ISSUE TITLE
Wait for events from Tasks

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#18]
I need to implement a C# interface that contains a method that is called by C# code.

The method returns a `Task<Operation>` and the task blocks until some operation is available.

I implement the interface in a class called `OStream`. My current approach for the method is:

```csharp
public Task<Operation> Get()
{
  return Task.Factory.StartNew(() =>
  {
    // wait for an event that satisfies some predicate 
    var eReq =
                    (EReq)
                        this.eventWaiter.WaitForEvent(
                            e => e is EReq);
    // notify some machine that this is the last event in this stream
    var eDone = new EStreamDone();
    PSharpRuntime.SendEvent(this.myNode, eDone, eDone);
    
    return eReq.operation;
  }
}
```

What is an `EventWaiter`? 

```csharp
    public class EventWaiter
    {
        private object monitor = new object();
        private IList<Event> events = new List<Event>();

        public Event WaitForEvent(Func<Event, bool> pred)
        {
           ...
        }

        public void PutEvent(Event e)
        {
           ...
        }
    }

```

The `OStream` class also creates a machine that has a reference to the event waiter and when it receives events, it calls `PutEvent` (inter-Task communication! Naughty!). 

This works fine for me, but involves locks and inter-Task communication via the shared `events` list.

**Comment by pdeligia** [comment]
Related to this: now P# has basic support for waiting on events f97e583e51c36b8cf45a82ab55dd818244026800

Note that this feature is still experimental and requires more polishing and testing to make sure it is robust. It also currently only works on machines that do not have intra-machine concurrency (e.g. explicitly spawned TPL tasks or async/await). This should be addressed next.

The APIs to use can be found here:

https://github.com/p-org/PSharp/blob/master/Source/Core/Library/Machine.cs#L281
https://github.com/p-org/PSharp/blob/master/Source/Core/Library/Machine.cs#L295
