### ISSUE TITLE
Make MachineId and Machine generic

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#187]
What do you think of this?

Some machines and events:

```csharp
// Human events.
class HumanEvent : Event { }

// Dog events.
class DogEvent : Event { }
class DogHelloEvent : DogEvent { }

// Human: accepts any Event.
class Human : Machine<Event> { }
// Dog: accepts only Dog events.
class Dog : Machine<DogEvent> { }
```

Example use:

```csharp
class Program
{
    static void Main(string[] args)
    {
        // Pretend this is our P# runtime.
        var r = new MyRuntime();

        // Create a Human machine.
        var h = r.Create<Human>();
        // Can send any Event. No compile error:
        r.Send(h, new DogEvent());


        // Create a Dog machine.
        var d = r.Create<Dog, DogEvent>();
        // Can only send Dog events.
        r.Send(d, new DogEvent());
        r.Send(d, new DogHelloEvent());
        // Compile error:
        r.Send(d, new HumanEvent());

        // Cannot create a Dog that accepts HumanEvents. Compile error:
        var d2 = r.Create<Dog, HumanEvent>();
    }
}
```

The fact that you have to specify an event type when creating the machine is annoying, but I'm not sure how to work around that in C#.

If `Dog` was an actor (with a single `HandleEvent` method), the event received would be of the correct type as well. I don't think you could currently enforce it in machines though.

**Comment by akashlal** [comment]
Can you spell this out more? For instance, the `MachineId` is also generic? And the `Runtime.Send` operation is typed as the following? 

` Send<T>(MachineId<T>, T event)` 

I don't see any other way of getting a compiler error.

This is useful, but I don't think its useful enough. I would actually like the `MachineId` to tell me statically what machine it represents. Currently I find myself naming the `MachineId` variable to carry the machine type name. 

Also, with many machines, fitting the set of events they accept on the Event subtyping relation might be too restrictive. I would like to explore the possibility of building a custom static analysis and then supporting something like what P supports with interfaces.

**Comment by paulthomson** [comment]
You got it. And it is indeed rather limited and so maybe isn't worth implementing. I think typed/interface actors is the ideal approach.
