### ISSUE TITLE
Build instructions missing BuildTools and PSharpBinaries requirements.

### ISSUE THREAD

**Issue by jlennox** [p-org/PSharp#188]
If _BuildTools_ is not installed, the call to `MSBuildWorkspace.Create()` causes a `TypeLoadException` for `Microsoft.Build`. _BuildTools for Visual Studio 2015_ works with Visual Studio 2017. Link: http://www.microsoft.com/en-us/download/details.aspx?id=48159

The `PSharpBinaries` environment variable is required for compiling. It can be set like: `xset PSharpBinaries C:\code\PSharp\Binaries` and then Visual Studio restarted.

~~Will submit PR.~~ (I did not realize this was not in a .md file)

**Comment by pdeligia** [comment]
Thanks for reporting these issues @jlennox!

**Comment by nesteruk** [comment]
I think you meant to write `setx` instead of `xset`.
