### ISSUE TITLE
Merge `HasFinished` and `ConfigureNextIteration` in `ISchedulingStrategy`

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#189]
These two methods should be merged so that when you call `ConfigureNextIteration`, false is returned if there are no more iterations.

Sidenote: maybe change the name to `PrepareForNextIteration/Schedule`? There is no configuring here.

E.g. in DFS, in `PrepareForNextIteration`, the strategy will pop elements from a stack to backtrack the search. It is then easy to check if there are more schedules to execute. `HasFinished` **is only ever called immediately before** `PrepareForNextIteration` so is redundant and it is hard to efficiently implement `HasFinished` since it is called first (before backtracking the stack) and could in theory be called at any time (but in practice, it won't be).

**Comment by pdeligia** [comment]
Sounds good!

**Comment by pdeligia** [comment]
Done in #195.
