### ISSUE TITLE
Create new projects for ISchedulingStrategy

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#190]
I imagine:

SchedulingStrategyAPI:
* ISchedulingStrategy
* IProcessInfo (or similar)
* SchedulingStrategyException

SchedulingStrategies:
* DFSSchedulingStrategy
* DPORSchedulingStrategy
* etc.

These two projects will not depend on any other P# projects, except that `SchedulingStrategies` depends on `SchedulingStrategyAPI`.
The `TestingServices` project will depend on these projects.

Thus, `SchedulingStrategyAPI.dll` and `SchedulingStrategies.dll` will be produced, which can be used in other projects. Furthermore, people can write their own schedulers, producing a dll that depends solely on `SchedulingStrategyAPI.dll`.

**Comment by pdeligia** [comment]
This is an awesome idea and we should do it when we free up some time from other tasks. What I did in #195 is already going towards addressing this (but more stuff need to be done).

**Comment by paulthomson** [comment]
We discussed that maybe one project containing the API and the built-in scheduling strategies would also be OK.

As part of this, we should also change all existing strategies to not take the `Configuration` in their constructors; instead, just pass the fields they need (e.g. usually just `MaxSteps`). In fact, `ProbabilisticRandomStrategy` currently takes both `Configuration` and `Configuration.CoinFlipBound`! :D

**Comment by pdeligia** [comment]
Done in #208.
