### ISSUE TITLE
Use instructions for a new project fail to mention required assembly reference

### ISSUE THREAD

**Issue by gordonwatts** [p-org/PSharp#197]
Just working through a simple example, I couldn't get past the build phase because of a missing reference:

    <Reference Include="Microsoft.PSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c4566cf0a7f74012, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(PSharpBinaries)\Microsoft.PSharp.dll</HintPath>
    </Reference>

Adding that should probably be done about where the .targets are added. I was looking here for instructions: https://github.com/p-org/PSharp/wiki/Visual-Studio-Editing-Support

**Comment by gordonwatts** [comment]
I also see some template projects - where I cut the above code from, btw.

**Comment by pdeligia** [comment]
Have you build the `PSharp.sln` solution (in the root directory)? This will generate the `Microsoft.PSharp.dll` that is missing above. See instructions here: https://github.com/p-org/PSharp/wiki/Build-Instructions

**Comment by pdeligia** [comment]
I updated https://github.com/p-org/PSharp/wiki/Visual-Studio-Editing-Support to point to the building instructions.

**Comment by gordonwatts** [comment]
Ops - sorry - obviously wasn't clear. Yes, the build worked fine. The dll was built. The issue is with creating a new empty project and getting it setup to use PSharp. In the steps you miss adding the PSharp dll to the list of references. And since you want to do it via a environment variable, this requires editing the solution file (at least in my limited experience with Visual Studio). Sorry for the confusion!

**Comment by pdeligia** [comment]
Oh I see, sorry for the confusion! Note that the instructions in https://github.com/p-org/PSharp/wiki/Visual-Studio-Editing-Support are only required if you want to write P# programs using the high-level syntax of P# (example [here](https://github.com/p-org/PSharp/blob/master/Samples/PingPong/PingPong.PSharpLanguage/Server.psharp)). If you want to use P# as a C# library (example [here](https://github.com/p-org/PSharp/blob/master/Samples/PingPong/PingPong.PSharpLibrary/Client.cs)), then the only thing you need to do is to reference the `Microsoft.PSharp.dll` from your C# project. I updated the https://github.com/p-org/PSharp/wiki/Visual-Studio-Editing-Support to add a bit of clarity. Thanks a lot for reporting this!
