### ISSUE TITLE
Building master may be tricky due to MSBuild/dotnet issue

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#199]
To build from the command line, I had to install the command line version of the .NET Core SDK:
https://www.microsoft.com/net/core#windowscmd

That was not even enough: I had to do:
`set MSBuildSDKsPath=C:\Program Files\dotnet\sdk\1.0.4\Sdks`
See:
https://stackoverflow.com/questions/42837264/missing-include-for-netstandard-project-when-building-on-build-server

Building from VS2017 does not seem to work.

**Comment by paulthomson** [comment]
Setting the `MSBuildSDKsPath` environment variable fixes building in VS2017.

**Comment by pdeligia** [comment]
@akashlal @t-rasmud guys did any of you had any VS2017 issues like @paulthomson ?

**Comment by paulthomson** [comment]
I don't see this issue now so maybe I just needed to restart or something.
