### ISSUE TITLE
Expose P# as a framework

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#2]
We would like to have full VS support, which would dramatically increase productivity. This is a really complicated matter though, especially due to how the P# parsing currently is done in a three phase approach. There are some suggestions:

(1) Directly extend Roslyn AST
(2) Extend the P# parser to handle advanced C# expressions/statements
(3) Embed P# as a C# framework

I am more inclined to do (1) or (2) as (3) would be too verbose and maybe harder to control? Have to think more about this ...

**Comment by paulthomson** [comment]
I'll add my suggestion.

(4) Use C# to C# translation.

* Provide dummy C# classes and some templates (examples) such that it is possible to specify machines in C# succinctly. 
* Use Roslyn to parse and visit the AST of the succinct C# and generate the actual C# code that will be executed.

This gives you several things for free:
* VS support (Intellisense, errors shown in VS, etc.)
* C# error detection.
* Some basic error detection for mis-use of the P# API. 

Example:
````C#
    using static Events;
    using static Server.States;
    using static P;
    
    public enum Events { Ping, Pong, Unit, Timeout };

    // "Machine" is a dummy class to mark the fact
    // that this is a machine.
    // It may have dummy methods too.
    // The real Machine class will have a different name or be in a different namespace.
    // The actual Server class will be generated by the visitor (perhaps in a different namespace again).
    class Server : Machine 
    {
        // STATES
        public enum States { Playing, Waiting };

        // FIELDS
        private readonly Machine client;
        
        // STATE TRANSITIONS
        
        // Init state
        public Server()
        {
            // This will not actually be the constructor of the generated 
            // Server machine, but this seems like a good way to 
            // specify the Init state.

            // Use of "new" on a machine type will be replaced with code that creates the machine.
            client = new Client(this);
            Raise(Unit);
        }

        // Use of attributes is one way to specify (with Intellisense) state transitions. 
        // There might be a better (cleaner) way.
        // The visitor will check the structure of the method and that every event is handled, etc.
        [State(Playing)]
        public void PlayingBody()
        {
            Send(client, Pong);

            On(Ping).GoTo(Playing);
            // Or:
            On(Ping, Playing);
            // Or (named parameter):
            On(Ping, GoTo: Playing);
        }

        
    }
````

And a variation without comments:

````C#
    using static Events;
    using static Server.States;
    using static P;
    
    public enum Events { Ping, Pong, Unit, Timeout };

    class Server : Machine 
    {
        public enum States { Playing, Waiting };

        private readonly Machine client;

        public Server()
        {
            client = new Client(this);
            Raise(Unit);
        }

        [State(Playing)]
        public void PlayingBody()
        {
            Send(client, Pong);

            On(Ping, Playing);
            On(Pong, Waiting);
        }
        
        // ...
        
    }
````

The visitor would generate a class for each event specified, etc. It would generate a ServerMachine class, which would include bits of code parsed from Server. Calls like "Send" and "On" will be replaced with the respective P# API call. The visitor would have to enforce the various constraints. E.g. you must specify the events, you must handle all events at the end of a "state transition method", etc.

**Comment by pdeligia** [comment]
This is what I am experimenting with right now:

```C#
using System;
using Microsoft.PSharp;

namespace PingPong
{
    internal class Server : Machine
    {
        MachineId Client;

		[Initial]
		[OnEventGotoState(typeof(Unit), typeof(Playing))]
		class Init : MachineState
        {
            Server Fields;

            protected override void OnEntry()
            {
                (this.Machine as Server).Client = this.CreateMachine(typeof(Client), this);
                this.Raise(new Unit());
            }
        }

		[OnEventDoAction(typeof(Unit), "SendPong")]
        [OnEventDoAction(typeof(Ping), "SendPong")]
        class Playing : MachineState
        {
            protected override void OnEntry()
            {
                this.Send((this.Machine as Server).Client, new Pong());
            }
        }

        void SendPong()
        {
            this.Send(this.Client, new Pong());
        }
    }
}
```

I quite like the use of attributes to declare transitions and action handlers, which will then be picked up by the P# compiler and translated to the intermediate C# representation. I am not entirely happy though with the States. Currently to access a field from the machine you have to do (this.Machine as Foo).Field, which is quite verbose ... I am trying to think a clean solution for this. Btw, internally states are just nested classes to a machine, which makes sense to have them as classes even on the frontend. Any thoughts/suggestions?

**Comment by pdeligia** [comment]
Some more thoughts. This could end up being quite easy to use and not too verbose:

```C#
using System;
using Microsoft.PSharp;

namespace PingPong
{
    internal class Server : Machine
    {
        MachineId Client;

		[Initial]
        [OnEntryDoAction("InitOnEntry")]
        [OnExitDoAction("InitOnExit")]
        [OnEventGotoState(typeof(Unit), typeof(Playing))]
        [DeferEvents(typeof(Foo))]
        [IgnoreEvents(typeof(Bar), typeof(Baz))]
        class Init : MachineState { }

		void InitOnEntry()
        {
            this.Client = this.CreateMachine(typeof(Client), this);
            this.Raise(new Unit());
        }

		[OnEventDoAction(typeof(Unit), "SendPong")]
        [OnEventDoAction(typeof(Ping), "SendPong")]
        class Playing : MachineState
        {
            protected override void OnEntry()
            {
                this.Send((this.Machine as Server).Client, new Pong());
            }
        }

        void SendPong()
        {
            this.Send(this.Client, new Pong());
        }
    }
}
```

You can still write a state like before (which is the actual translation):

```C#
[Initial]
[OnEventGotoState(typeof(Unit), typeof(Playing))]
class Init : MachineState
{
    protected override void OnEntry()
    {
        (this.Machine as Server).Client = this.CreateMachine(typeof(Client), this);
        this.Raise(new Unit());
     }
}
```

But if you want less verbosity you have the above option using attributes!

**Comment by pdeligia** [comment]
Done exposing a cleaner framework for now. The static checking (to make sure someone does not write whatever he wants) needs a bit more work but will expose and merge meanwhile so we can start using this.

**Comment by pdeligia** [comment]
I have implemented some static checking too the last few days. Closing this issue for now.
