### ISSUE TITLE
Last part of bug trace went to console

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [p-org/PSharp#20]
On one of my bug-finding runs (without /v, so the bug trace would normally go to a file), the last ~250 lines of the ~1000-line bug trace went to the console.  Theory of how this happened: Scheduler.KillRemainingTasks didn't kill all tasks because of a data race on this.Tasks, and then Runtime.WaitMachines got an AggregateException as soon as the _first_ task was killed (see [Task.WaitAll documentation](https://msdn.microsoft.com/en-us/library/dd270695(v=vs.110).aspx)) and returned without waiting for the rest of the tasks, so output was redirected back to the console while tasks were still running.

I've only seen this once and it wasn't with the latest version of P#, but if you think the problem could still happen, you may want to fix it.  (Looks like P# could use some systematic concurrency testing!)

**Comment by pdeligia** [comment]
Hi Matt, were all the tasks in your case captured by the P# scheduler? Or it could be that the P# runtime was oblivious to the existence of some of these tasks? Just trying to think how to reproduce this race, or an example were the `KillRemainingTasks()` would race on `this.Tasks`.

**Comment by mattmccutchen-microsoft** [comment]
> an example were the ```KillRemainingTasks()``  would race on ```this.Tasks```.

Discussed privately.  The better way to explain this is that KillRemainingTasks could run while a machine is in the body of Send, and that machine may unblock the receiving machine and start a new machine task for it (which won't have been killed) before calling Schedule and dying.

**Comment by paulthomson** [comment]
I may have observed something similar just now. 

In `RandomStrategy.TryGetNext`, there is a call to `tasks.Where(...)`. An `InvalidOperationException` was thrown with details: "Collection was modified; enumeration operation may not execute." 

I believe other tasks were executing `BugFindingScheduler.KillRemainingTasks` from within a call to `Schedule`.

**Comment by pdeligia** [comment]
Yep there must be a race there when tasks are getting killed (I also observed it in some runs). Was a bit busy this week so had no time to look into this yet, we should try to get it fixed soon.

**Comment by pdeligia** [comment]
I believe this is fixed now, so closing this issue (until further notice).
