### ISSUE TITLE
New methods to be used when nesting scheduling strategies

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#209]
We are already using nested scheduling strategies, where some scheduling strategy may defer a scheduling decision to another scheduling strategy. In general, a strategy may need to know about what decisions are being made "behind its back", but it depends.

For example, I want to add a simple strategy that forces scheduling of all non-send operations. If the child strategy is PCT, then it is probably fine for PCT to not know about these "forced" scheduling operations and so it will only increase its step count on Sends. 

On the other hand, the LivenessCheckingStrategy is not aiming to hide visible operations from the child strategy; instead, it wishes to sometimes take control, but the child strategy could still be informed of the decisions being made. E.g. PCT as a child strategy would update its step count and could also do a priority change. DPOR (and radomized DPOR) as a child strategy *must* know exactly what visible operations occur, else it will break.

Thus, I think `ISchedulingStrategy` will need to have methods like:

* `ForceNext(List<ISchedulable> choices, ISchedulable current, ISchedulable forcedChoice)`
* `ForceNextBoolean(...)`
* `ForceNextInteger(...)`

Hopefully, the implementations of these methods will be empty for simple strategies (e.g. Random) and minimal for others.

**Comment by pdeligia** [comment]
Done in caef75f0f7665323c88508f6a4c911ed192146ea.
