### ISSUE TITLE
Data races on PSharpRuntime.MachineMap

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#21]
This is similar to #13

We are sometimes getting a `KeyNotFoundException` when sending an event. It again seems to be the case that a machine is "missing" from `PSharpRuntime.MachineMap`.  

I am not quite sure of the exact sequence of events that causes this, but it does at least look like there is a data race on `PSharpRuntime.MachineMap`. If two machines are being created concurrently, then `PSharpRuntime.MachineMap` is being added to by both threads concurrently. Of course, other threads are also potentially reading from this map (which can be mutated at any time) when doing sends and so these reads should also be protected. Perhaps a thread safe map would be better.

If performance becomes an issue later, we could consider alternative solutions.

**Comment by pdeligia** [comment]
Hi Paul, maybe we can use a `ConcurrentDictionary` (https://msdn.microsoft.com/en-us/library/dd287191(v=vs.110).aspx) which is thread-safe. Could you please replace this locally and let me know if it works in your test case?

Only the real execution runtime should need this change (as no machines ever run concurrency in bug-finding mode):

https://github.com/p-org/PSharp/blob/master/Source/Runtimes/Runtime/Runtime.cs#L37
