### ISSUE TITLE
Most scheduling strategies increment their step count when doing nondet choice; they probably shouldn't

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#212]
E.g. in PCT, the number of nondet choices made by a thread during a visible operation should probably not influence where the priority change points are added.

**Comment by pdeligia** [comment]
I am not entirely sure about that. I thought about that before, but it can mess up with liveness checker (or at least it could before). Also, you might want to have a strategy that inserts "delays" for nondet choices (so its not 50-50 for example). Saying this, you could achieve this without having to increment the step count, so perhaps you are right.

**Comment by pdeligia** [comment]
Closing this issue for now.
