### ISSUE TITLE
The liveness checking strategies should (eventually) be moved to the scheduling strategies project

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#213]
This is good engineering and will also allow them to be used outside of P#.

I suggest that the runtime provides (to the ISchedulingStrategy, via the ISchedulable interface or another interface) a way to get the state hash of each ISchedulable or a way to get the state hash of all ISchedulables. Thus, the strategy can then decide when to do this and how to store it, depending on how it does reduction.

**Comment by pdeligia** [comment]
Also needs an interface for a liveness monitor (hot/cold states), this shoudn't be too hard. We could do it when we have free cycles.

**Comment by pdeligia** [comment]
Closing this issue.
