### ISSUE TITLE
Data race on MachineTasks

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#22]
In `TaskMachineScheduler`, the `MachineTasks` field is accessed without a lock. I don't know if this matters though. If it doesn't matter, you could add a comment.

**Comment by pdeligia** [comment]
I don't think it matters because the `TaskMachineScheduler` is only used during bug-finding (and we might end up completely changing this in the near future -- its very experimental) -- on that thought, I should probably disable this feature and only use it via a command line option.

**Comment by pdeligia** [comment]
Task scheduling is optional and can be enabled using `/tpl`, see de10ed77387d068fc326d3f3f33eee46e0301e70
