### ISSUE TITLE
Allowing to continue from a trace after the state diverges

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#223]
Nar: I have some traces that take 20000 iterations to get. However when I fix the first bug, it goes past and stops because the traces diverge. It will be great if it proceeded further and let it go where the code takes it. This will considerably reduce my testing time. I think this will also help save the rare traces to help repro later.

**Comment by akashlal** [comment]
@pdeligia Lets discuss this feature some time next week.

**Comment by pdeligia** [comment]
@akashlal sounds good

**Comment by pdeligia** [comment]
Lets create a nested scheduler that tries to replay initially the trace (until it cannot replay anymore) and then switch to the normal testing strategy.

**Comment by pdeligia** [comment]
Done in #228.
