### ISSUE TITLE
OnHalt callback

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#235]
Introduce a callback (`async` method preferably) in `Machine` that is called when the machine is about to be halted. This will give the user a chance to clean up state. One can do this currently by handling the `Halt` event, but this will have to be done for all states of the machine.

**Comment by shazqadeer** [comment]
My understanding of this feature is that this callback is invoked subsequent to unwinding the entire state stack of the halting machine and setting the "halted" status of the machine to true.  In this interpretation, the callback should be executing only non-P# code, i.e., it should not invoke any APIs for creating machines, receiving events, or sending events.
