### ISSUE TITLE
.NET Core is a dependency

### ISSUE THREAD

**Issue by shazqadeer** [p-org/PSharp#259]
.NET Core is an explicit dependency of build.ps1.  As far as I know, .NET Core is not installed when VS 2017 is installed.  In that case, shouldn't .NET Core be listed as an explicit dependency of P#?

**Comment by pdeligia** [comment]
.NET Core is actually part of the VS 2017 installation (but you need to enable the option in the installed components, else it will not install by default). I will add this note to our documentation for clarification.
