### ISSUE TITLE
Fix CustomLoggerTest

### ISSUE THREAD

**Issue by anirudhsanthiar** [p-org/PSharp#261]
CustomLoggerTest needs to be updated to account for 
1. The new SendLog and EnqueueLog format (without target machine state)
2. GUID reporting (as per https://github.com/p-org/PSharp/commit/362d66c41c516d25553dcf48c00dd944f7174ba7)
Right now, the GUID assigned to the operation group according to this test is "00000000-0000-0000-0000-000000000000". This is converted to "----" by `Regex.Replace(logger.ToString(), "[0-9]", "");`, whereas the test expects "<none>"

**Comment by akashlal** [comment]
Already fixed. Closing.
