### ISSUE TITLE
Redundant procedure NotifyRaisedEvent

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#265]
This guy seems redundant:
```C#
        internal virtual void NotifyRaisedEvent(Machine machine, EventInfo eventInfo, Guid? operationGroupId)
```

Given that there is already:

```C#
        internal virtual void NotifyRaisedEvent(Monitor monitor, EventInfo eventInfo)
```

And the former is only called with `null` as the third argument.

**Comment by TedHartMS** [comment]
This is one of several pairs of overloaded function pairs where first param is Machine vs. Monitor

**Comment by akashlal** [comment]
Ah, got it. But I did some cleanup anyway via f3b2f0f
