### ISSUE TITLE
WriteLine for <PushLog> is incorrect

### ISSUE THREAD

**Issue by ellab123** [p-org/PSharp#272]
This line in StateMachineLogger.cs:
this.WriteLine($"<PushLog> Machine '{0}' pushed from state '{1}' to state '{2}'.",
                    machineId, currentStateName, newStateName);

prints:
<PushLog> Machine '0' pushed from state '1' to state '2'.

It should be replaced with:
this.WriteLine($"<PushLog> Machine '{machineId}' pushed from state '{currentStateName}' to state '{newStateName}'.");

**Comment by akashlal** [comment]
Thanks Ella. Fixed in 59ff737
