### ISSUE TITLE
Rewriter target always assumes a PSharp input

### ISSUE THREAD

**Issue by muwaqar** [p-org/PSharp#306]
Rewriter build target always assumes the project has a PSharp input file:

https://github.com/p-org/PSharp/blob/520e8eb5cc390a0b3147d30ac455c689b2d174d6/Tools/Compilation/SyntaxRewriter/Program.cs#L184

This makes the compilation of the project fail with the following error if the project in fact did not contain any PSharp file.

`The Rewriter task failed unexpectedly. System.NullReferenceException: Object reference not set to an instance of an object.`

The stack trace points to Line 186 of Program.cs (mentioned above) though (instead of 184) (using Microsoft.PSharp 1.3.5).

**Comment by akashlal** [comment]
Thanks. This was a known issue. The fix is already in master and will be made available in the next release:
https://github.com/p-org/PSharp/blob/master/Tools/Compilation/SyntaxRewriter/Program.cs#L186
