### ISSUE TITLE
Equivalent for P's `null` event / transition?

### ISSUE THREAD

**Issue by alexreinking** [p-org/PSharp#359]
In plain P, we can write a machine like this one:

```
machine M {
  start state S {
    entry { print "Entry!\n"; }
    on null do { print "Queue is empty!\n"; }
  }
}
```
Null transitions are called whenever the machine is scheduled and performs a dequeue operation while the queue is empty. So this program would print the following as long as the machine keeps getting scheduled.
```
Entry!
Queue is empty!
Queue is empty!
...
```
How do we get this behavior in P#?

I'm working on the P->P# translation with @ankushdesai

**Comment by akashlal** [comment]
It’s called Default:
https://github.com/p-org/PSharp/blob/master/Source/Core/Runtime/Events/Default.cs

**Comment by akashlal** [comment]
Closing; let me know if there are any followups.

**Comment by alexreinking** [comment]
Thanks, @akashlal
