### ISSUE TITLE
Default values for Assume and Assert annotations on Events

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#366]
What should be the default values for assume and assert annotations on events.
In P, -1 represents no bounds. Is it the same in P#?

**Comment by pdeligia** [comment]
Hi Ankush, that is correct. The default constructor is setting both to `-1`:

https://github.com/p-org/PSharp/blob/master/Source/Core/Runtime/Events/Event.cs#L38

**Comment by ankushdesai** [comment]
Thanks !!
