### ISSUE TITLE
Running PSharpTester on Generated P# code

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#367]
I am struggling a bit to get the P->PSharp pipeline work smoothly.
I am generating a dll (as well as .cs) file from P compiler. 
But passing the dll to PSharpTester

```
C:\Workspace\MyGitHub\PSharp\bin\net46 [master ≡]> .\PSharpTester.exe /test:Main.dll
. Testing Main.dll
Error: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Error: Failed to load assembly 'Main, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

Do you have suggestions on how I should go about this part?
What is thebest  suggested output from P compiler to PSharpTester.

@shazqadeer

**Comment by ankushdesai** [comment]
Also, the dll is generated with TargetFramework as <TargetFramework>netcoreapp2.1</TargetFramework> could that be a problem?

**Comment by shazqadeer** [comment]
If Main.dll is generated with .NET Core, then you have to use the .NET core version of P#.  There should be a folder for it in the P# nuget package.

**Comment by ankushdesai** [comment]
Aah, my bad. That was easy, thanks for the quick response.
