### ISSUE TITLE
Support for Goto<>() with parameter

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#369]
The Goto statement in P# does not support passing parameters. Please correct me if I am wrong.

In P, one can do:

`goto S, 10;`

and 10 is passed as an input parameter to the state entry function.

This feature is not supported currently in P->P# translation and throws exception. 
There are two solutions (1) support Goto with parameters (2) allow external code to update ReceiveEvent (it is not settable currently) so that the generated code can set it appropriately before entering the state.

Please let me know if you can support either of these.

@shazqadeer

**Comment by ankushdesai** [comment]
```
event x: int;
...

state S {
  entry {
    goto S1, 10;
  }
  on x goto S1;
}

state S1 {
  entry (payload: int) {
    assert(payload == 10);
  }
}
```

It is passed as an input parameter to the handler.

**Comment by akashlal** [comment]
Hi Ankush,
How about a simple workaround? You create a field in every machine called say `LastTrigger`. On a `goto`, stash the argument to this guy. On any method that needs to access the `payload` will get it from this field. Works? No need to use `ReceivedEvent`.

**Comment by ankushdesai** [comment]
It complicates things a bit as it means that I will have to handle the case when a machine enters a state using goto differently then when it enters the state using send or raise.

**Comment by akashlal** [comment]
But you have to do something like this anyway because P# doesn't allow handlers with parameters. How do you encode an entry procedure with a payload right now?

**Comment by ankushdesai** [comment]
The input parameter is always initialized to the value of the payload in the ReceivedEvent.

**Comment by akashlal** [comment]
Alright, then instead of:

InputParam = ReceivedEvent;

Do:

If(LocalPayload != null) {
   InputParam = LocalPayload;
   LocalPayload = null;
} else {
   InputParam = ReceivedEvent;
}

Works?

I’d rather avoid user-facing changes if possible.

Akash

**Comment by ankushdesai** [comment]
This solution has been implemented in the P compiler. Thanks, Akash for the help!
