### ISSUE TITLE
Publish .NET Core builds to Nuget

### ISSUE THREAD

**Issue by alexreinking** [p-org/PSharp#370]
Currently, the [Microsoft.PSharp](https://www.nuget.org/packages/Microsoft.PSharp/) NuGet package only supports .NET Framework projects. It would be good to make `netstandard2.1` builds available so we don't have to import P#'s source code as a Git submodule in the P compiler repo.

The last release was 1.3.5, 8 months ago. When will the next release be made available? I see there are tags for versions 1.3.6 - 1.3.9 and the README instructs users to get the "latest" release from NuGet.

**Comment by akashlal** [comment]
We plan to have a new package uploaded on nuget.org next week.

**Comment by alexreinking** [comment]
Thanks, Akash. Will that version of P# support .NET Core?

**Comment by pdeligia** [comment]
Yes!

**Comment by alexreinking** [comment]
Awesome! 😄

**Comment by alexreinking** [comment]
Was there a delay, here?

**Comment by shazqadeer** [comment]
Is this lack of control on the process only because this is the first time through the new process?  If this nondeterminism is possible every time a fresh release is published on nuget, perhaps we need to consider a new process.

**Comment by akashlal** [comment]
This is a one time thing and we are close now.

Akash

**Comment by alexreinking** [comment]
Any updates?

**Comment by pdeligia** [comment]
@alexreinking we finally got unblocked and our package is ready. We need to go through some final admin processing to be able to upload to nuget.org (as there were very strict new requirements that were put in place for public MS-owned packages and we had to conform, this is what caused this massive delay). Please note that both @akashlal and me are OOF soon for a week or so, so might not be able to get the final green light before that. But its coming very soon now. Thanks for your patience.

**Comment by pdeligia** [comment]
@alexreinking @shazqadeer we are now finally able to publish again! I just uploaded the latest NuGet package (1.4.0) which should be indexed very soon and available for consumption. Closing this issue.

**Comment by alexreinking** [comment]
Hooray! I see [1.4.0](https://www.nuget.org/packages/Microsoft.PSharp/1.4.0) in the Nuget Gallery already!
