### ISSUE TITLE
Emulating P's stack unwinding for raise, goto, pop

### ISSUE THREAD

**Issue by alexreinking** [p-org/PSharp#371]
In plain P, the following code
```
machine M {
  start state S1 {
    entry {
      print "foo\n";
      goto S2;
      print "unreachable\n";
    }
  }
  state S2 {
    entry { print "bar\n"; }
  }
}
```
prints
```
foo
bar
```
because `goto` acts as an exception that is caught by the runtime. The default behavior of [`this.Goto`](https://github.com/p-org/PSharp/blob/master/Source/Core/Runtime/Machines/Machine.cs#L367) in `Machine` in P# is to insert a special event in the `RaisedEvent` field which is handled _after_ the caller finishes executing.

In P this must happen immediately, so when we translate this code to P#, we throw a `PNonStandardReturnException` which is handled by `OnException` by returning `OnExceptionOutcome.HandledException` for such cases.

However, this creates a lot of noise in logging. We would like to add an `OnExceptionOutcome.QuietlyHandledException` or maybe `OnExceptionOutcome.IntentionalException` (the name is unimportant) such that the runtime swallows the exception without logging.

**Comment by akashlal** [comment]
Hi Alex, 
How about that every handler looks as follows:

```
void SuperHandler()
{
   try {
     Handler();
   }
   catch(PNonStandardReturnExeption ex) {
      this.Goto(ex.TargetState);
   }
}
```

Then you do no use the `OnException` method and no useless chatter. Will this work?

**Comment by alexreinking** [comment]
I had that thought, too, but unfortunately it will not work in general. Here's an example program that demonstrates why (in my opinion) this is best done in the runtime:
```
event E; event F;
machine M {
  state S {
    entry {
      send this, F;
      foo(); // [A]
      assert false; // raise in foo makes this unreachable
    }
    on F do foo; // [B]
    on E do { print "E\n"; }
  }
  fun foo () {
    raise E;
  }
}
```
Now, if we translate `foo()` with the `try { ... } catch (...) { ... }` you suggested, then the call at `[A]` will return and the assertion will be triggered (bad behavior). On the other hand, if we do not translate `foo` with that try-catch, then the call triggered by F (at `[B]`) will throw an exception up to the runtime.

So there are several solutions for this problem:

1. **(my preferred)** We simply throw an exception that we can silently handle (as I described in my original post) to unwind the stack. This results in needing to generate only one additional line of code per call to Raise/Pop/Goto (RPG).
2. Like above, the full exception handler could be marked `virtual` (like `OnException` is now) so we can override the behavior in our own subclass.
3. For each event action, we generate a wrapper function that operates with that `try-catch` model. This results in an additional function per `on` and will delay JIT-ing. Hopefully, the real function would be inlined quickly.
4. We give up on exceptions and reimplement stack unwinding manually, generating checks after every function call to see whether we need to return early. This adds a lot of branching to the generated code.

Generating idiomatic C#/P# code that implements P's semantics as directly as possible is a central design goal. The more complicated the code we generate is, the more likely there will be subtle bugs in larger programs.

**Comment by akashlal** [comment]
Hi Alex,
My suggestion was more along the lines of "3". That is, the following:
`on e do foo`
is translated to: `[OnEventDoAction(typeof(e), nameof(SuperFoo))]` and then `SuperFoo` invokes `foo` inside the `try-catch` block. 

Alternatively, you can override the Logger to suppress such exceptions. P# allows for a custom `ILogger`. Simplest is if you override the default P# logger. It might give you flexibility in other places as well to control the amount of logging.

I agree about having the P to P# translation process as simple as possible. However, inheriting changes in the P# runtime takes time. Special casing for just one exception type seems too nuanced for a runtime. 

I would suggest that you move ahead without blocking on changes to P# whenever possible. Once you near feature completion, we can step back and discuss possible simplifications that P# can provide.

**Comment by ankushBoL** [comment]
Thanks, Akash!
I would suggest we go with the overriding of `ILogger` as the solution. This would ensure that our generated code is simple. It will also give us control over how/what exceptions we throw in the generated code and ignore them in the visible log.

**Comment by ankushdesai** [comment]
Thanks, Akash!
I would suggest we go with the overriding of ILogger as the solution. This would ensure that our generated code is simple. It will also give us control over how/what exceptions we throw in the generated code and ignore them in the visible log.

**Comment by ankushdesai** [comment]
This has been implemented in the P compiler, we just override the two functions related to the HandledException in MachineLogger class. Thanks, Akash for the help!
