### ISSUE TITLE
How to run a [Test] from code?

### ISSUE THREAD

**Issue by alexreinking** [p-org/PSharp#379]
In our automated tests for the P->P# translation, we want to be able to invoke `PSharpTester.exe` / `PSharpTester.dll` (depending on the target) reliably. As a stop-gap, we're detecting the location of the tester executable (windows-only) via reflection:
```
using Microsoft.PSharp.TestingServices;
string pSharpAssemblyLocation = Path.GetDirectoryName(typeof(TestingEngineFactory).GetTypeInfo().Assembly.Location);
string testerPath = Path.Combine(pSharpAssemblyLocation, "..", "net46", "PSharpTester.exe");
```
What would be _ideal_ is to generate a `.csproj` containing a package reference to P# and a `Main()` function that invokes the tester on a generated `[Test]`, eg.
```
public class Program {
    [Microsoft.PSharp.Test] // maybe don't need this?
    public static void GeneratedExecute(PSharpRuntime runtime) {
        runtime.RegisterMonitor(typeof(SomeGeneratedMonitor));
        runtime.CreateMachine(typeof(SomeGeneratedMachine));
    }
    public static void Main(string[] args) {
        // maybe typeof(Program) instead? whatever is easiest
        PSharpTester.RunTest(GeneratedExecute);
    }
}
```
This breaks the dependence on the executable location and automatically adapts to net46/netcoreapp2.1 builds. Is there already some API for doing this?

**Comment by akashlal** [comment]
You can run PSharp tests programmatically as well. See [this sample](https://github.com/p-org/PSharpLab/blob/master/TestSamples/CoreAppTestProject/UnitTest1.cs). Does this help? Or perhaps I didn't understand your question.

**Comment by akashlal** [comment]
Closing the issue. Ping back if your question wasn't resolved.
