### ISSUE TITLE
The Iteration option

### ISSUE THREAD

**Issue by kailiangji** [p-org/PSharp#380]
Hi,
When I try to use the `/i:[N]' option in PSharpTester.exe, it always report the following error:
```
 ./PSharpTester.exe /i:20 /test:../../Samples/Language/bin/net46/PingPong.exe
Error: cannot recognise command line option 'i:20'
```

**Comment by akashlal** [comment]
You're probably trying this on linux? The `/` is eaten up by the linux console. I'm not sure what is the best option here. @pdeligia?

**Comment by pdeligia** [comment]
We could add an alternative prefix symbol eg ‘-‘, and the user can choose which they prefer/works. What do you think?

We can make ‘-‘ the default (in documentation) to be compatible with both platforms, but leave ‘/‘ for backwards compatibility.


________________________________

**Comment by akashlal** [comment]
ok, sounds like the right thing to do. Is there a quick fix, e.g., some way of passing a `/` on the linux console?

**Comment by pdeligia** [comment]
Hmm, I am not aware of a quick fix for this. I don’t have access to a terminal to try, but I wonder if there is a way to escape the character. I can try to push a proper fix later today though.


________________________________

**Comment by TedHartMS** [comment]
StackOverflow indicates doubling the forward slash ("//xxx") should escape it

**Comment by kailiangji** [comment]
I don't think this is the problem caused by OS. In fact I am working under Windows 10.  The parameter `/timeout:N` could be identified correctly.

**Comment by akashlal** [comment]
In that case, I'm not sure what is going on. I don't understand how you're invoking the tester as `./PSharpTester.exe` (as opposed to `.\PSharpTester.exe`). What console are you using?

**Comment by kailiangji** [comment]
I am using Git Bash

**Comment by akashlal** [comment]
Try windows command prompt instead.

**Comment by kailiangji** [comment]
Yes, It works. Thank you!
