### ISSUE TITLE
How do I specify portfolio testing strategy?

### ISSUE THREAD

**Issue by shazqadeer** [p-org/PSharp#393]
I see the following output:

PSharpTester.exe /sch:x
Error: Please give a valid scheduling strategy '/sch:[x]', where [x] is 'random', 'pct' or 'dfs' (other experimental strategies also exist, but are not listed here).

I would like to use the portfolio strategy.  How do I specify that?

**Comment by akashlal** [comment]
`/sch:portfolio` The help message is outdated.
