### ISSUE TITLE
Error trace output of PSharpTester

### ISSUE THREAD

**Issue by shazqadeer** [p-org/PSharp#394]
I am running PSharpTester in P# release 1.4.0.  The ouput file with the suffix .pstrace has output like the following which is different from the error trace output I am used to from earlier versions of P#.  Has anything changed? 

<BugTrace xmlns="http://schemas.datacontract.org/2004/07/Microsoft.PSharp.TestingServices.Tracing.Error" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Steps><BugTraceStep z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"><EventInfo xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.PSharp"><a:EventName>PrtSharp._GodMachine+Config</a:EventName><a:OriginInfo i:nil="true" xmlns:b="http://schemas.datacontract.org/2004/07/Microsoft.PSharp.Runtime"/></EventInfo><ExtraInfo i:nil="true"/><InvokedAction i:nil="true"/><Machine i:nil="true" xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.PSharp"/><MachineState i:nil="true"/><RandomBooleanChoice i:nil="true"/><RandomIntegerChoice i:nil="true"/><TargetMachine xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.PSharp"><a:Endpoint/><a:Generation>0</a:Generation><a:Name>PrtSharp._GodMachine(1)</a:Name><a:NameValue/><a:Type>PrtSharp._GodMachine</a:Type><a:Value>1</a:Value></TargetMachine><Type>CreateMachine</Type></BugTraceStep><BugTraceStep z:Id="i2" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/"><EventInfo i:nil="true" xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.PSharp"/><ExtraInfo i:nil="true"/><InvokedAction i:nil="true"/><Machine xmlns:a="http://schemas.datacontract.org/2004/07/Microsoft.PSharp"><a:Endpoint/><a:Generation>0</a:Generation><a:Name>PrtSharp._GodMachine(1)

**Comment by akashlal** [comment]
PSharpTester spits out three files `.pstrace`, `.schedule` and `.txt`. The last one is probably what you want. It has the log generated from the buggy run. The file `.pstrace` is for the [Trace Viewer](https://github.com/p-org/PSharp/blob/master/Docs/Tools/TraceViewer.md) and the `.schedule` file is for the [Replayer](https://github.com/p-org/PSharp/blob/master/Docs/Testing/TestingMethodology.md#reproducing-and-debugging-traces).

**Comment by akashlal** [comment]
Please reopen if the question remains unanswered.
