### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by shazqadeer** [p-org/PSharp#40]
I just synced up and tried to clean and rebuild PSharp.sln.  I got the following errors:

Severity	Code	Description	Project	File	Line
Error		Metadata file 'C:\Users\qadeer\Work\PSharp\Binaries\Debug\Microsoft.PSharp.SystematicTesting.dll' could not be found	SystematicTesting.Tests.Unit	C:\Users\qadeer\Work\PSharp\Test\SystematicTesting.Tests.Unit\CSC	
Error		Metadata file 'C:\Users\qadeer\Work\PSharp\Binaries\Debug\Microsoft.PSharp.SystematicTesting.dll' could not be found	Tester	C:\Users\qadeer\Work\PSharp\Tools\Tester\CSC

**Comment by pdeligia** [comment]
Hi Shaz, can you try build in Release mode? Is this only happening in the Debug build? I cant seem to reproduce this. From the error description it seems the SystematicTesting.dll is not being picked up by these 2 projects.

**Comment by shazqadeer** [comment]
I looked more carefully.  A couple  of dependencies on SystematicTesting were missing in PSharp.sln.  I added those and now it works fine for me.  I have checked my changes in.  Please take a look.
