### ISSUE TITLE
Design of P# Program Visualizer

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#41]
@p-org/p-developers @p-org/psharp-developers 
Dear P and P# developers and users,
We are designing a visualization tool for P# programs and would like your opinion on it. The feature is checked into "visualization" branch of P#. The program visualizer summaries information from multiple runs of a P# programs and displays it in graphical format (with state machines and transitions). The user can interact with the tool to create their own view of the program. 

There is a usage manual here:
https://github.com/p-org/PSharp/blob/visualization/Docs/Visualizer/VisualizerUsage.pdf

What do you think? We'd love to hear from you.

Akash & Pantazis

**Comment by paulthomson** [comment]
This looks great! I would propose that the input to the visualizer tool is a log file (or set of log files). Thus, the tool could be used with P or even any other tools/languages that output the recognized log file format.

**Comment by pdeligia** [comment]
Addressed in #50.
