### ISSUE TITLE
Investigate InboxFlushOperationTest nondeterministically failing some times

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#412]
Most of the time this test passes, but some times it fails.

**Comment by akashlal** [comment]
I've not been able to repro this issue, even after several thousand runs on my machine. And the code seems fine. Any way we can set up a reliable repro?

**Comment by pdeligia** [comment]
Closing this as old timer implementation is deprecated. New timers do this differently (by ignoring timeouts that originate from a disposed timer).
