### ISSUE TITLE
Manual link broken on http://p-org.github.io/PSharp/

### ISSUE THREAD

**Issue by CraigStuntz** [p-org/PSharp#43]
On http://p-org.github.io/PSharp/ it says:

> A good way to start is by reading [the manual](https://cdn.rawgit.com/p-org/PSharp/master/Docs/Manual/out/manual.pdf) (which is quite outdated right now, a new version will get released soon, but in the meantime please feel free to contact the P# dev team with specific questions).

The link is broken, but there *is* a maual, updated within the last two months, at https://github.com/p-org/PSharp/blob/master/Docs/Manual/manual.pdf

**Comment by pdeligia** [comment]
Thanks @CraigStuntz - the link is now fixed.
