### ISSUE TITLE
Question regarding /coverage:activity

### ISSUE THREAD

**Issue by ankushdesai** [p-org/PSharp#470]
> A tuple (M, S, E) is said to be covered by a test run if state S of machine M actually dequeues an event of type E during an execution.

**Questions**: Is receive (implemented using PSharp await) covered as well ?

**Comment by pdeligia** [comment]
If I am not wrong, we do not include receive statements in the activity coverage today. Is that correct, @akashlal?

**Comment by akashlal** [comment]
Receive does count against the activity coverage. See references of the method `ReportActivityCoverageOfReceivedEvent`. It is called both on dequeue as well as on Receive.

**Comment by ankushdesai** [comment]
Great, thanks!
