### ISSUE TITLE
TraceViewer Crashing on Open

### ISSUE THREAD

**Issue by jzhang919** [p-org/PSharp#476]
Hi all:

I've successfully built P# and the Trace Viewer tool from source. But Trace Viewer is crashing when I click on "File->Open Trace:" I've also tried passing in the .pstrace file on the command line, but it opens the exe again with no trace.

How do I fix this?

Best,
James

**Comment by ankushdesai** [comment]
Hi @jzhang919, What platform are you using? I have tried it on Windows and it works fine.

**Comment by jzhang919** [comment]
Windows. We can try on Mac. What's the process for Mac, since MacOS doesn't support .exe?

**Comment by jzhang919** [comment]
Bump: Tried building TraceViewer again for a particularly strange bug, and was able to fix the crashing issue.

However, opening the .pstrace in question yields a  "Bug trace Raft_0_0.pstrace is not readable. Please make sure you selected a '.pstrace' file."

Any ideas on debugging this issue? I've uploaded the .pstrace [here](https://drive.google.com/open?id=1Y7tgHdgw9JvUMTALnemNm-39Kg71d4ZP) if that is helpful.

**Comment by pdeligia** [comment]
Hi @jzhang919, most of the teams that use P# in production use their own favorite text editor to view and filter through the buggy traces. For this reason, we have not updated TraceViewer in a long time now, and are not actively maintaining it to minimize overhead.

To set the expectations right, we just moved TraceViewer to its own repository [here](https://github.com/p-org/TraceViewer), still under the `p-org` organization. Although we are not actively working on this tool anymore, its open-source under the MIT license, and PRs for improvements and bug-fixes are more than welcome!
