### ISSUE TITLE
Should `Receive` be async?

### ISSUE THREAD

**Issue by paulthomson** [p-org/PSharp#63]
If `Receive` (the method that allows a machine to block inside an action to receive an event) is not a hack (i.e. not a last resort that users should avoid), then perhaps it should be async. If you had 100s of machines using the blocking `Receive` method, then you could end up having 100s of blocked `Task`s which would exhaust the thread pool. `Task`s are not supposed to be used like this. It can cause serious performance issues. 

Making an async version of `Receive` would solve this. You would also need to allow async action handlers, but these would only be needed when async `Receive` is used. 

An alternative quick fix would be to allow `Task`s for certain machines to get their own thread in the thread pool (mark them as `LongRunning`). This is still not a real fix as you can end up with more threads than the number of threads in the thread pool.

**Comment by akashlal** [comment]
Thanks Paul. If I understand this correctly, by making Receive async, the user can then do an await on it to block for the result? In C#, the control goes back to the caller. In P#, it is unclear what the benefits would be if users simply do "await Receive" all the time. Is this somehow more efficient with its use of Tasks?

Akash

**Comment by paulthomson** [comment]
> Is this somehow more efficient with its use of Tasks?

Yes I believe so :)

Basically, if the "await Receive" blocks then instead of the actual action handler (and Task, and thread) being blocked, the entire action handler returns (assuming an async action handler). The P# runtime can then return and the Task completes. The thread is now free to be used by another Task. Depending on how you implement this, I think the Task that represents resuming from the await will get rescheduled automatically once you notify the TaskCompletionSource that the Receive implementation awaits on (or something like that). Or maybe you can store and continue this Task explicitly (which might be easier). 

I guess this might not be too important right now, but if you think people will care about the performance of Receive (and they will have lots of blocking Receives) then I think it will be important eventually! :)

**Comment by pdeligia** [comment]
Hey Paul, I totally agree with your argument regarding performance benefits!

Btw, Receive is not a hack, in the sense that its a core API of the language that people are free to use. I anticipate that its use (and how much of it) depends really on the user application (e.g. the Fabric/Orleans model we implemented with @t-rasmud heavily uses it).

Saying this, its really tricky to support async-await inside P#: would probably need to change lots of stuff (e.g. the bug-finding scheduler since its not obvious how to properly schedule async-await, as you do not have explicit control of the tasks, maybe the static analysis, and parts of the compiler to spit out the async-await methods). This is a lot of engineering effort. I actually had thought about adding async-await support before, but I was put off from the amount of designing/refactoring that it requires (and testing to make sure it works correctly). But maybe the effort to support async-await inside P# is less than I imagine, I need to sit down and properly think about this.

I agree that this should be done at some point though (assuming there is no better solution, using TPL).  Should we keep this as a long-term TODO for P#? Any suggestions? Maybe we can make this issue as the place to draft potential designs for supporting this.

**Comment by paulthomson** [comment]
Cool! I agree that it would need more thought and I haven't thought about it yet! Long-term TODO sounds about right!

**Comment by pdeligia** [comment]
Btw, we might be able to get around not changing the bug-finding scheduler/runtime! The various P# components are really modular right now (although this can surely improve even more :-)). I can imagine a solution where async-await is only done for production, and for testing we simply use vanilla TPL.

**Comment by narganapathy** [comment]
Personally I would rather avoid using the async/await keywords in PSharp APIs. The reason is as follows. PSharp forces you to make everything async (i.e., you have events and then handlers and handles are not supposed to block). For the same reason, I would encourage all the APIs to not block at all (like this.Receive).

**Comment by paulthomson** [comment]
I also like the idea of no blocking at all in the P# API. Does this mean you don't use `Receive`?

**Comment by narganapathy** [comment]
No. We will use a delegate model with this.Receive. Something like this.receive(event type, delegate)  where delegate is launched when the event is received. This is already one of the options for Receive.

**Comment by paulthomson** [comment]
Ah I see this now. This is a nice solution except I think that Receive currently still blocks the caller (and, thus, the current Task and current thread from the thread pool) until an appropriate event is received. Also, a recent commit simplifies the receive statement, removing the option of using Actions/delegates. See #73.

A solution would be for Receive to not block the caller, but still store an Action. The Action is then just like a temporary handler that is "set" by the Receive statement. The P# runtime would then schedule the Action similar to other event handlers. 

```csharp
// an event handler executed to handle some event.
void Handler()
{
  this.Send(...);
  // Does not block:
  this.Receive(typeof(EDone), (e) => {
    // Handle e here.
    // Could even have another (nested) receive. 
  });
  // Execution continues. The lambda is set (temporarily) to handle EDone events. 
  // The lambda will not execute until this handler returns,
  // even if an EDone event is already in the queue.
  // Could enforce/encourage an immediate return here?
}
```

This might be a bit confusing but avoids blocking a thread from the thread pool, which is essential if/when performance matters (and assuming a lot of Receives). And it completely avoids async/await!

**Comment by pdeligia** [comment]
I think that I really like what Paul suggested! We discussed a bit about this earlier with @akashlal / @t-rasmud, and let me recap.

I wonder if a nice idea would be something that builds upon what Paul suggested above:

**[the below is just a draft, feel free to comment suggestions]**

- Receive statement should be the last executed statement in an action (i.e. it should have a return statement after similar to a goto/raise).
- Receive statement basically _temporarily defers_ all events _except_ the one(s) that the machine is waiting to receive. In this sense, a machine is not blocked (and thus no thread/task is being blocked), and we use the defer semantics of P# to achieve a receive functionality. When a machine receives one of the expected types (+ an optional predicate as implemented already), then the machine will un-defer every temporarily deferred event, handle the received event with the specified action handler.

One limitation with the above approach is that we cannot do this:
```
void Handler()
{
  ...
  this.Receive(...);
  ...
  this.Receive(...);
  ...
  this.Receive(...);
  ...
}
```
which might make the above pattern more tedius to write. However, we could introduce **P#-continuations** (to not be confused with Task continuations). Basically, when you call receive, you could also define an optional continuation, which is an action handler to execute as soon as the received handler has executed (and has priority over dequeue, similar to a raise statement). Of course, this continuation handler can also receive (as the last statement), and so on.

**Comment by pdeligia** [comment]
I also forgot to add that everything we discuss might be potentially problematic, since we allow a receive statement to be called from **outside** a P# machine. Runtime provides a receive method (https://github.com/p-org/PSharp/blob/master/Libraries/Core/Runtime/Runtime.cs#L228).

We cannot really enforce a return stmt after a receive outside a P# machine, since the compiler does not touch this code and simply passes it to Roslyn.

If we also implement the above, we need to make sure that calling Receive from outside a P# machine, does not break the new semantics, and still does not block a task/thread.

**Comment by akashlal** [comment]
Well, if you are going to have receive as the last statement, can't you instead do a push, go to a new state that defers all except what you want, handle it, then pop?

Receive is slightly simpler syntax than creating a state, but the above is not too bad I think.

Akash

**Comment by pdeligia** [comment]
Yes, you are absolutely right about this.

**Comment by paulthomson** [comment]
@akashlal I think one of the advantages of the Receive syntax is that you can provide a lambda and so can refer to local variables from in the handler. Thus, like in P, you don't need additional fields and a separate handler method. 

@pdeligia  Regarding multiple Receives, you could do the following. But the runtime would have to be implemented carefully so that the action field in the machine (that stores the receive action) is cleared just before being executed. Thus, it can be set again from within the action. 

```csharp
void Handler()
{
  this.Send(..);
  this.Receive(typeof(EDone), (e) => {
  this.Send(..);
  this.Receive(typeof(EDone), (e) => {
  this.Send(..);
  this.Receive(typeof(EDone), (e) => {
  // ...
  });
  });
  });
}
```

Regarding the enforcing of return (for Raise and possibly Receive): I have never liked the idea of enforcing this. I would just let the user "set" a raised event and "set" a receive action. The event/action that is set will be read once the handler returns. The DSL->C# compiler can be more restrictive and ensure that a return is always generated. If you still want P# as a library to enforce this, you could throw an exception, but this might be slow. Or, make it so that all handlers must return some special type to indicate whether they want to raise (or receive) an event. E.g.

```csharp
Result Handler()
{
  // raise
  if(...)
  {
    return new Raise(typeof(EEGoToWaiting));
    // Or, if you don't want `new`, have a method that returns the appropriate type:
    // return this.Raise(typeof(EEGoToWaiting));
  }
  
  return DoneResult(); // normal case, or could just return null. 
}
```

Thus, the only way to raise is to return a certain object. Receive could be done similarly. This has no slowdown (like with exceptions) and no analysis is needed. Arbitrary methods could also raise/receive by returning an object and assuming that the caller will return this object in the handler.

**Comment by akashlal** [comment]
Interesting suggestion Paul. I will need to think about this.

Akash

**Comment by pdeligia** [comment]
Hi Paul,

> Result Handler()
> {
>   // raise
>   if(...)
>   {
>     return new Raise(typeof(EEGoToWaiting));
>     // Or, if you don't want `new`, have a method that returns the appropriate type:
>     // return this.Raise(typeof(EEGoToWaiting));
>   }
> 
>   return DoneResult(); // normal case, or could just return null. 
> }
> Thus, the only way to raise is to return a certain object. Receive could be done similarly. This has no slowdown (like with exceptions) and no analysis is needed. Arbitrary methods could also raise/receive by returning an object and assuming that the caller will return this object in the handler.
> 
This is really interesting idea. Yes, I definitely do not want to throw exceptions for control-flow, as it is slow, and error-prone since the user can catch it. But returning an object of appropriate type to indicate raise or receive or default case is interesting indeed.

**Comment by narganapathy** [comment]
FWIW, I thought This.receive() didn't block if it had a delegate. Is this not the case ?

**Comment by akashlal** [comment]
It wasn't :)

**Comment by paulthomson** [comment]
Just to confirm, do you mean Receive was not non-blocking? :-) i.e. Receive blocks and always has, even with delegates.

**Comment by pdeligia** [comment]
We added support for `async`/`await` in #148. With these changes, the `receive` statement is now `async`.
