### ISSUE TITLE
Support generic machines

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#65]
Might be nice to add support for:

class Foo<T> : Machine { ... }

and

machine<T> { ... }

**Comment by akashlal** [comment]
Is there something missing in what you said?

**Comment by pdeligia** [comment]
The runtime certainly complains about it, when I tried earlier today (it would allow us to cleanly reuse some code between Orleans and Fabric), and I am not sure if the parser supports it. I need to investigate to which extend its not supported, it could be just few hours of work.

**Comment by paulthomson** [comment]
(Note: the example from the first post includes generics when I view it on GitHub.)

**Comment by pdeligia** [comment]
Oh I see now what you meant @akashlal @paulthomson  Unless you put \ before \\<>, then the generic type disappears from markdown! I edited my post later :-)

**Comment by pdeligia** [comment]
#66 implements initial support (only for machines, not monitors, and only in the library level)
