### ISSUE TITLE
OnEventGotoState silently overrides OnEventDoAction

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [p-org/PSharp#7]
In code using the P# framework APIs, I wanted an event to trigger both an action and a state transition.  I overlooked the three-argument form of OnEventGotoState and tried to specify both OnEventDoAction and OnEventGotoState, which resulted in the action not running.  Instead, this should be a compile-time error.  (Low priority because the correct way to do this is stated in the manual.)

**Comment by pdeligia** [comment]
Hi Matt, this should indeed be an error, I will add this as a compiler-error soon! Thanks for catching this.

**Comment by pdeligia** [comment]
This is fixed in bfffde7dcc26ca2ca9a80a703cee989a81af1598. The compiler should report an error if a state declares more than one handler for a particular event.
