### ISSUE TITLE
Syntactic sugar for state transitions

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#79]
(Requested by Nar)

1. 

Wildcard matching: 
       `on * do action;`
    or:
       `on * except e1, e2 do action;`

2.

Transitions common to all states should be declared on one place. For example we add `on Timeout goto Terminating` on all states in one shot.

**Comment by pdeligia** [comment]
Regarding (2) could possibly be done by installing these handlers on the machine class declaration.

We should make sure any syntactic sugar is also reflected in P#-as-a-library, e.g. for the on * do, se could have either a new attribute [OnAnyEventDo(optional set of excepted events, action)] or create a special event Any (i prefer a new attribute though). Similar for ignore: [IgnoreAllEventsExcept(...)].

We should make sure the semantics are clear: can we have handlers on foo do x, when we have on * do y? maybe these should be exclusive, or the explicit handler overwrites the wildcard.

**Comment by akashlal** [comment]
Superceeded bu #92. Closing this one.
