### ISSUE TITLE
Support for liveness property checking

### ISSUE THREAD

**Issue by pdeligia** [p-org/PSharp#8]
I am currently implementing liveness property checking (basic support is done, the advanced features are implemented/tested in a new branch), similar to how P does this. This feature can be enabled using the `/liveness` command line option.

I give below a few different cases of how it can be used, and try to quickly explain it for now.

Case 1) The assumption in this case is that you have written a **terminating** harness. You can specify a liveness monitor as follows:
```C#
class M : Monitor
{
        [Start]
        [OnEventGotoState(typeof(Waiting), typeof(CanGetUserInput)]
        [OnEventGotoState(typeof(Computing), typeof(CannotGetUserInput)]
        class CanGetUserInput : MachineState { }

        [Hot]
        [OnEventGotoState(typeof(Waiting), typeof(CanGetUserInput)]
        [OnEventGotoState(typeof(Computing), typeof(CannotGetUserInput)]
        class CannotGetUserInput : MachineState { }
}
```
Notice the `Hot` attribute (can only be attached on a Monitor state). This denotes a state that progress is being waited to be made. If the program terminates and the monitor is in a **hot** state, then there is a liveness bug. You should make sure to transition a monitor to a non-hot state if the liveness property is satisfied (e.g. a node that just came up, received the data from the master). This way you can specify liveness properties as safety properties. But again reminder that this requires a terminating harness.

Case 2) The harness does not need to be terminating (e.g. can have infinite execution). You can write the  same monitor as above. The P# runtime will perform some internal program state-caching (do not confuse with a machine state) and use it (together with the program trace) to identify a *lasso* (i.e. loop back to a previous program state). Then it will compute if this loop is a **fair** execution. If its not fair then it does nothing. If it is a fair execution, then it will check if the monitor was in a hot state at some point in the lasso. If yes, then it reports a liveness bug and exits.

Case 3) Same as above, but now you can write the following monitor:
```C#
class M : Monitor
{
        [Start]
        [Cold]
        [OnEventGotoState(typeof(Waiting), typeof(CanGetUserInput)]
        [OnEventGotoState(typeof(Computing), typeof(CannotGetUserInput)]
        class CanGetUserInput : MachineState { }

        [Hot]
        [OnEventGotoState(typeof(Waiting), typeof(CanGetUserInput)]
        [OnEventGotoState(typeof(Computing), typeof(CannotGetUserInput)]
        class CannotGetUserInput : MachineState { }
}
```
Note the `Cold` attribute (can only be attached on a Monitor state). This denotes a state that progress has been made. Follow the same algorithm as above. If there is a visited hot state and no cold state in the monitor during the loop, then report a liveness bug. Else skip the iteration as you just found an infinite loop that does not lead anywhere.

**Comment by pdeligia** [comment]
Btw, case 1 is already supported in master branch.

**Comment by shazqadeer** [comment]
A note about 2.  The visit to the hot state must have been in the loop of the lasso for the execution to be declared an error.  If the hot state is visited and exited before the loop starts, then it is not an error.

**Comment by desaiankush** [comment]
A note on 1). I would still suggest first trying the random sampling
algorithm like MaceMC on non-terminating programs. This would be useful as
a comparison metric before trying the complicated caching approach.
-> Can you first convert Chengs example into non-terminating.
-> Try the random sampling method with large bound (10000) and see if you
find the error.
-> This will also confirm whether in reality such approaches give false
positives. In my experience, they dont until you hand craft some examples
where MaceMC fails.

**Comment by pdeligia** [comment]
@shazqadeer that is correct: I should say "in a hot state at some point in the lasso" instead of "in a hot state at some point in the execution".

@desaiankush thats a good suggestion, I will try to check that at some point during the weekend (as support for checking it already exists so it should be easy). i do not have a good intuition though about your last point, but i am also curious regarding it.

**Comment by pdeligia** [comment]
Liveness checking has been implemented, so closing this issue.
