### ISSUE TITLE
Remove /t:test flag

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#81]
We should remove the /t flag from the compiler. Regardless of testing or execution, we should produce an exe (or what the project targets). Running the tester on an exe should not be an issue.

**Comment by pdeligia** [comment]
This is partially done in the improve_compilation branch, and I can push soon.

Btw I could not remove the /t:test option yet. The main reason is that we need the project/solution be compiled in debug mode for testing (eg so we can break with the replayer). I enforce this when using /t:test, this is the only difference between using it vs not using it. Any suggestions?

**Comment by akashlal** [comment]
We can let the user choose debug or release. Then, as is usual, the debugging experience isn't nice if the user chose release. Would that be acceptable? Or can the tester reject if the dll is in release?

Akash

**Comment by pdeligia** [comment]
Btw, compiling with Roslyn gives you the option to choose between two _optimization levels_: Debug and Release. There is a P# compiler flag for doing so called `/optimization:{debug|release}`. This seems to be different from the _build configuration_ debug|release|custom, which made me realise that we are currently probably always building using the debug configuration (this seems to be related to #80). I am not sure how can we check if a exe/dll is in release or debug? Maybe when you load the assembly, you can check some parameter? We should figure out how to better integrate with MSBuild so we can build for release in production.

I am also not sure if rejecting an exe/dll with the Tester is more acceptable than forcing the user to explicitly choose during compilation.

**Comment by akashlal** [comment]
What will go wrong if we try to test/replay a release exe/dll?

**Comment by akashlal** [comment]
Resolved with 2401c4be01fc72d35d123ab90063cb3e67caa371.
PSharpCompiler isn't necessary to build any more.
