### ISSUE TITLE
Further Tester statistics

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#83]
In place of:
`Instrumented 154 scheduling points (on last iteration).`
We should say:
`Average scheduling points in terminating executions: blah`

It is useful to know the "expected" length of execution of a program. What do you think?

**Comment by pdeligia** [comment]
My only worry is programs with unfair infinite executions. But we can maybe (also) show median value?

**Comment by akashlal** [comment]
We only average across executions that terminate normally (i.e., not hit the bound). Perhaps min and max would also be useful to show.

**Comment by pdeligia** [comment]
Addressed in #84
