### ISSUE TITLE
Deferred event is being ignored instead

### ISSUE THREAD

**Issue by mattmccutchen-microsoft** [p-org/PSharp#9]
I noticed that an event I declared as deferred was not being processed at all.  It looks like a simple mistake here:

https://github.com/p-org/PSharp/blob/ec7ed0481b37d808cc9a9d45ecc965786165fccb/Source/Core/Library/MachineState.cs#L185

**Comment by mattmccutchen-microsoft** [comment]
BTW, it would have been helpful to log something at https://github.com/p-org/PSharp/blob/9530489cdbed0df829dcca9de3a6b042f3307272/Source/Core/Library/Machine.cs#L476 when an event is ignored.

**Comment by pdeligia** [comment]
Thanks for the bug report, and great suggestion about the logging! Btw, one reason I was not logging before is that you could have a machine that keeps sending events (flooding the inbox) and thus an ignore log could potentially make the trace too long. But I have many levels of verbosity. I could easily enable ignore/defer event logging in a higher verbosity level (typically I use 2, but 3 has some extra logging).

**Comment by pdeligia** [comment]
Bug fixed in 72f59a8d5f658c41f6e5da5b158aa37fe95fad41. Also now logging ignored events with /v:3.
