### ISSUE TITLE
ignoring raise event

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#93]
The current code seems to apply ignored events to the raise event as well:
```
                // Checks if the raised event is ignored.
                if (this.IgnoredEvents.Contains(nextEventInfo.EventType))
                {
                    nextEventInfo = null;
                }
```

My understanding is that in P, ignore/defer does not apply to the raised event. @shazqadeer

**Comment by shazqadeer** [comment]
ignore E is simply shorthand for installing a empty action handler on E

on E do {}

So, ignore E would apply if R is raised.

defer E is a policy on the dequeueing of events not to handling of events.  So, defer E has no connection with raising of E.

**Comment by akashlal** [comment]
Got it. No bug then :)
