### ISSUE TITLE
Assert raise/pop cannot be called from OnEntry and OnExit methods

### ISSUE THREAD

**Issue by akashlal** [p-org/PSharp#95]
This is enforced in P. Same for transition methods, such as `foo` in `on e goto S with foo`

**Comment by akashlal** [comment]
@shazqadeer Can you please clarify what is done in P? 
From our discussion, OnExit and transition methods cannot do raise or pop. What about OnEntry methods?

**Comment by akashlal** [comment]
I have addressed all this in the branch CheckedRaise. I will submit a pull request soon.

**Comment by pdeligia** [comment]
Hi guys, really quick comment from my side: any reason OnEntry should not raise (and thus goto/jump)? We are doing this in almost every sample so far :-)

**Comment by shazqadeer** [comment]
OnEntry can raise and pop.  So can action handlers.

**Comment by pdeligia** [comment]
Addressed in #99
